// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using T2Su.Models;

namespace T2Su.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20210819030216_Tabela")]
    partial class Tabela
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("T2Su.Models.Cadastro", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Cadastros");
                });

            modelBuilder.Entity("T2Su.Models.Cate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Categoria")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cates");
                });

            modelBuilder.Entity("T2Su.Models.Escolha", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Escolhas");
                });

            modelBuilder.Entity("T2Su.Models.Registro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CadastroId")
                        .HasColumnType("int");

                    b.Property<int>("CateId")
                        .HasColumnType("int");

                    b.Property<string>("Cliente")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CodigodeContainer")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<DateTime>("DataDeFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("EscolhaId")
                        .HasColumnType("int");

                    b.Property<int>("TipomoviId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CadastroId");

                    b.HasIndex("CateId");

                    b.HasIndex("EscolhaId");

                    b.HasIndex("TipomoviId");

                    b.ToTable("Registros");
                });

            modelBuilder.Entity("T2Su.Models.Tipomovi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Tipodemovimentação")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tipomovis");
                });

            modelBuilder.Entity("T2Su.Models.Registro", b =>
                {
                    b.HasOne("T2Su.Models.Cadastro", "Cadastro")
                        .WithMany("Registros")
                        .HasForeignKey("CadastroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("T2Su.Models.Cate", "Cate")
                        .WithMany("Registros")
                        .HasForeignKey("CateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("T2Su.Models.Escolha", "Escolha")
                        .WithMany("Registros")
                        .HasForeignKey("EscolhaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("T2Su.Models.Tipomovi", "Tipomovi")
                        .WithMany("Registros")
                        .HasForeignKey("TipomoviId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cadastro");

                    b.Navigation("Cate");

                    b.Navigation("Escolha");

                    b.Navigation("Tipomovi");
                });

            modelBuilder.Entity("T2Su.Models.Cadastro", b =>
                {
                    b.Navigation("Registros");
                });

            modelBuilder.Entity("T2Su.Models.Cate", b =>
                {
                    b.Navigation("Registros");
                });

            modelBuilder.Entity("T2Su.Models.Escolha", b =>
                {
                    b.Navigation("Registros");
                });

            modelBuilder.Entity("T2Su.Models.Tipomovi", b =>
                {
                    b.Navigation("Registros");
                });
#pragma warning restore 612, 618
        }
    }
}
